---
- hosts: '{{ target }}'
  #  strategy: debug
  gather_facts: False
  roles:
    - coreosbootstrap
  become: true
  vars:
      ansible_python_interpreter: /home/core/bin/python

  tasks:

    - name: Update
      block:

      - name: Update CoreOs
        command: "/usr/bin/update_engine_client -update"
        register: command_result
        failed_when: "'Initiating' not in command_result.stderr"


      - name: reboot CoreOs after update
        reboot:
           reboot_timeout: 120
           
      become: yes
      tags:
         - update

          
    - name: Create docker.service.d directory for custom.conf
      file:
         path: /etc/systemd/system/docker.service.d/
         state: directory


    - name: Configure custom systemd unit file override
      template:
         src: custom.conf
         dest: "/etc/systemd/system/docker.service.d/custom.conf"
         owner: "root"
         group: "root"
         mode: "0644"

    - name: Restart docker
      systemd:
        name: docker
        daemon_reload: yes
        state: started
        enabled: yes
        masked: no
      notify:
      - docker status

    - name: Installation
      block:
      - name: Transfer the script
        copy: src=kubeadm.sh dest=/home/core mode=0777


      - name: Install Kubernetes binaries
        shell: /home/core/kubeadm.sh >> k8s_install_log.txt   


      - name: Create manifests directory for kubeadm
        file:
         path: /etc/kubernetes/manifests/
         state: directory


      - name: Restart kubelet
        systemd:
          name: kubelet
          daemon_reload: yes
          state: restarted
          enabled: yes
          masked: no
        notify:
        - kubelet status
    
      become: yes
      tags:
         - install


    - name: Join node to master
      block:
      - name: Copy the join command to server location
        copy: src=join-command dest=/tmp/join-command.sh mode=0777

      - name: Join the node to cluster
        command: sh /tmp/join-command.sh
         
      become: yes
      tags: 
        - joining


  handlers:
    - name: docker status
      service: name=docker state=started
    - name: kubelet status
      service: name=kubelet state=started
  
